export const OUTPUT_POST_WIDTH = 600;
export const OUTPUT_POST_VIEWBOX_WIDTH = 500;
export const OUTPUT_SMALL_POST_WIDTH = 600;
export const OUTPUT_SMALL_POST_VIEWBOX_WIDTH = 600;
export const OUTPUT_POST_HEIGHT = 600;
export const OUTPUT_POST_VIEWBOX_HEIGHT = 500;
export const OUTPUT_SMALL_POST_HEIGHT = 315;
export const OUTPUT_SMALL_POST_VIEWBOX_HEIGHT = 315;
export const OUTPUT_POST_FONTSIZE_COEF = 1;
export const OUTPUT_SMALL_POST_FONTSIZE_COEF = 0.765;
export const SHOWN_POST_WIDTH = 460;
export const THEME_DEFAULT_WIDTH = 500;

export const API_URL = 'http://localhost:8888';